### ISSUE TITLE
Twitch package stops working after a few days.

### ISSUE THREAD

**Issue by derNiklaas** [codeoverflow-org/nodecg-io#102]
### Description
You have to restart the twitch package every few days. (4-7 days) 

### How to reproduce
Create a plugin that requires nodecg-io-twitch (example: [modwatch](https://github.com/derNiklaas/mod-watch))
Let it run for a few days.
The bot doesn't do anything after a few days.

### Error Log 
```
 ⚠️  ircv3 WARNING Reconnecting because the last ping took over 10 seconds
```

**Comment by LarsVomMars** [comment]
This [issue](https://github.com/d-fischer/twitch/issues/161) with the twitch package might be related. Although until now it's just the bug report as well.

**Comment by daniel0611** [comment]
We are using a static auth token which doesn't need refreshing and also will be the same after the restart. Therefore refreshing shouldn't be the problem . Still investigating what causes this....

**Comment by LarsVomMars** [comment]
Ohh, good to know. Didn't take a closer look at our service implementation ...

**Comment by daniel0611** [comment]
@derNiklaas the constructor of the twitch client has a `channels` parameter where you can set channels which the client will automatically join if it connects and authenticates. We're not using this because the framework doesn't care which channels to bot should join and each bundle has to do it manually.
When manually joining a channel using the `.join` method it joins but doesn't auto-rejoin when it reconnects. This seems to be the issue here.
I'll create a PR later this day to add a simplification method which joins a channel and also automatically rejoins on reconnects. From my testing this solves the issue but it would be nice if you could check out my changes once I created the PR and test if it also fixes the problem for you.

**Comment by derNiklaas** [comment]
Just wanted to give a quick update. 
I updated my setup to the PR 2 days ago. Will give another update in a few days (~5 days) or when I encounter another error.

**Comment by derNiklaas** [comment]
Update: Still get the same error. 
[2020-09-18T16:40:41.363Z] ⚠️  ircv3 WARNING Reconnecting because the last ping took over 10 seconds

Does the .join() Method auto reconnect?

**Comment by daniel0611** [comment]
@derNiklaas the client reconnects by itself automatically so the warning is fine if all bundles using the twitch service are still working normally and still receive all events/can send messages. Is it only the warning or did the bundles stop working again?
Also, have you updated all bundles that use the twitch service (e.g. ModWatch) to use the new join method of the mentioned PR?

**Comment by derNiklaas** [comment]
Oh, i was still using the old getNativeClient() function before the join(). Will try again in the next few days.

**Comment by derNiklaas** [comment]
Update: Looks like it's working. It still works after the "reconnecting" message.

**Comment by daniel0611** [comment]
That sounds good

**Comment by derNiklaas** [comment]
Plugin still works.

**Comment by daniel0611** [comment]
Mine instance is running since two weeks without problems, where it crashed about every day before. Therefore I'll merge the PR.
